# -*- coding: utf-8 -*-
"""Tic Tac Toe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GpNe8N3VNB3VFJcDcb8J-Td0t1HwLHmj
"""

#function is called from the updatelist().
def match(ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE):  
  '''
  This function checks if any winner move has been made
  and return True if ther has.
  '''
#value of the positions are checked to see if there is any match between three aligned places. 
  #These are the horizontal sets that can be matched
  if ONE == TWO and TWO == THREE and THREE == ONE:
    return True
  elif FOUR == FIVE and FIVE == SIX and FOUR == SIX:
    return True 
  elif SEVEN == EIGHT and EIGHT == NINE and SEVEN == NINE:
    return True
  #These are the diagonal sets that can be matched. 
  elif SEVEN == FIVE and FIVE == THREE and SEVEN == THREE: 
    return True
  elif ONE == FIVE and FIVE == NINE and ONE == NINE:
    return True
  #These are the vertical sets that can be matched. 
  elif ONE == FOUR and FOUR == SEVEN and ONE == SEVEN:
    return True
  elif TWO == FIVE and FIVE == EIGHT and TWO == EIGHT: 
    return True
  elif THREE == SIX and SIX == NINE and THREE == NINE: 
    return True
  else: 
    return False

#this is called by the main block and initializes the value of each position
def updatelist(guy1, guy2, player1_sign, player2_sign):
  '''
  This function updates the value of the matrix to the players' choice 
  and returns who won the game
  '''

  one = "1"
  two = "2"
  three = "3"
  four = "4"
  five = "5"
  six = "6"
  seven = "7"
  eight = "8"
  nine = "9"
#There are nine positions to be taken so the loop runs nine times.
  for i in range(1,10):
    #the block is called out for print
    boxdisplay(one, two, three, four, five, six, seven, eight, nine)
    #if i is odd then it is player 1's turn
    if i % 2 != 0:
      #players choice is taken
      player1_input = input("Choose the number you want to conquer, {}: ".format(guy1))
      #depending on the number the player choses the value of that number is changed to the player's sign i.e, X or O
      if player1_input == "1":
        one = player1_sign
        #once the value is changed the match function is called to check if anyone has won.
        if match(one, two, three, four, five, six, seven, eight, nine) == True:
          return "player1"
        #if no mathces are found by the eight turn, no sets of three can be made so the game is tied. 
        elif match(one, two, three, four, five, six, seven, eight, nine)==False and i == 8:
          return "tie"
        else:
          continue
      elif player1_input == "2":
        two = player1_sign
        if match(one, two, three, four, five, six, seven, eight, nine) == True:
          return "player1"
        elif match(one, two, three, four, five, six, seven, eight, nine)==False and i == 8:
          return "tie"
        else:
          continue
      elif player1_input == "3":
        three = player1_sign
        if match(one, two, three, four, five, six, seven, eight, nine) == True:
          return "player1"
        elif match(one, two, three, four, five, six, seven, eight, nine)==False and i == 8:
          return "tie"
        else:
          continue
      elif player1_input == "4":
        four = player1_sign
        if match(one, two, three, four, five, six, seven, eight, nine) == True:
          return "player1"
        elif match(one, two, three, four, five, six, seven, eight, nine)==False and i == 8:
          return "tie"
        else:
          continue
      elif player1_input == "5":
        five = player1_sign
        if match(one, two, three, four, five, six, seven, eight, nine) == True:
          return "player1"
        elif match(one, two, three, four, five, six, seven, eight, nine)==False and i == 8:
          return "tie"
        else:
          continue
      elif player1_input == "6":
        six = player1_sign
        if match(one, two, three, four, five, six, seven, eight, nine) == True:
          return "player1"
        elif match(one, two, three, four, five, six, seven, eight, nine)==False and i == 8:
          return "tie"
        else:
          continue
      elif player1_input == "7":
        seven = player1_sign
        if match(one, two, three, four, five, six, seven, eight, nine) == True:
          return "player1"
        elif match(one, two, three, four, five, six, seven, eight, nine)==False and i == 8:
          return "tie"
        else:
          continue
      elif player1_input == "8":
        eight = player1_sign
        if match(one, two, three, four, five, six, seven, eight, nine) == True:
          return "player1"
        elif match(one, two, three, four, five, six, seven, eight, nine)==False and i == 8:
          return "tie"
        else:
          continue
      elif player1_input == "9":
        nine = player1_sign
        if match(one, two, three, four, five, six, seven, eight, nine) == True:
          return "player1"
        elif match(one, two, three, four, five, six, seven, eight, nine)==False and i == 8:
          return "tie"
        else:
          continue
      else: 
        continue

                  
    #if i%2 is 0 then it player 2's turn      
    elif i % 2 == 0:
      #players choice is taken
      player2_input = input("Choose the number you want to conquer, {}: ".format(guy2))
      #depending on the number the player choses the value of that number is changed to the player's sign i.e, X or O
      if player2_input == "1":
        one = player2_sign
        #once the value is changed the match function is called to check if anyone has won.
        if match(one, two, three, four, five, six, seven, eight, nine) == True:
          return "player2"
        #if no matches can be made by the eight turn no set of three can me made so its a tie. 
        elif match(one, two, three, four, five, six, seven, eight, nine)==False and i == 8:
          return "tie"
        else:
          continue
      elif player2_input == "2":
        two = player2_sign
        if match(one, two, three, four, five, six, seven, eight, nine) == True:
          return "player2"
        elif match(one, two, three, four, five, six, seven, eight, nine)==False and i == 8:
          return "tie"
        else:
            continue
      elif player2_input == "3":
        three = player2_sign
        if match(one, two, three, four, five, six, seven, eight, nine) == True:
          return "player2"
        elif match(one, two, three, four, five, six, seven, eight, nine)==False and i == 8:
          return "tie"
        else:
          continue
      elif player2_input == "4":
        four = player2_sign
        if match(one, two, three, four, five, six, seven, eight, nine) == True:
          return "player2"
        elif match(one, two, three, four, five, six, seven, eight, nine)==False and i == 8:
          return "tie"
        else:
          continue
      elif player2_input == "5":
        five = player2_sign
        if match(one, two, three, four, five, six, seven, eight, nine) == True:
          return "player2"
        elif match(one, two, three, four, five, six, seven, eight, nine)==False and i == 8:
          return "tie"
        else:
          continue
      elif player2_input == "6":
        six = player2_sign
        if match(one, two, three, four, five, six, seven, eight, nine) == True:
          return "player2"
        elif match(one, two, three, four, five, six, seven, eight, nine)==False and i == 8:
          return "tie"
        else:
          continue
      elif player2_input == "7":
        seven = player2_sign 
        if match(one, two, three, four, five, six, seven, eight, nine) == True:
          return "player2"
        elif match(one, two, three, four, five, six, seven, eight, nine)==False and i == 8:
          return "tie"
        else:
          continue
      elif player2_input == "8":
        eight = player2_sign
        if match(one, two, three, four, five, six, seven, eight, nine) == True:
          return "player2"
        elif match(one, two, three, four, five, six, seven, eight, nine)==False and i == 8:
          return "tie"
        else:
          continue
      elif player2_input == "9":
        nine = player2_sign
        if match(one, two, three, four, five, six, seven, eight, nine) == True:
          return "player2"
        elif match(one, two, three, four, five, six, seven, eight, nine)==False and i == 8:
          return "tie"
        else:
          continue
      else: 
        continue

#code to print the box with the numbers. 
def boxdisplay(ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE):
  '''
  This function print the XO box for the players to see
  '''
  #since .format() is in use, the variable input can be changed to any string. 
  print("{} | {} | {}".format(ONE, TWO, THREE))
  print("---------")
  print("{} | {} | {}".format(FOUR, FIVE, SIX))
  print("---------")
  print("{} | {} | {}".format(SEVEN, EIGHT, NINE))

#Accepting the players names
player1 = input("Player 1, enter your name: ")
player2 = input("Player 2, enter your name: ")

#Assigning the players either X or O
player1_symbol = str.upper(input("{}, chose one of X or O: ".format(player1)))

if player1_symbol == "X":
  player2_symbol = "O"
  print("{}, your sign is O".format(player2))
else: 
  player2_symbol = "X"
  print("{}, your sign is X".format(player2))
  
print("{}, your sign is {}".format(player1, player1_symbol))

game_on = "Y"

#The loop is run back to back games with rerun of the programme.
while(game_on == "Y"):
  result = updatelist(player1, player2, player1_symbol, player2_symbol)

  if result == "player1":
    print("{} has won".format(player1))
  elif result == "player2":
    print("{} has won".format(player2))
  elif result == "tie":
    print("The game is a TIE, but someone has to be a winner")
  #if the players respond "N" the loop will break and game will end.
  game_on = str.upper(input("PLAY AGAIN Y/N?: "))
  if game_on == "N":
    print("GAME OVER")
  else:
    continue